version: '3'

vars:
  app_name: Last Run
  app_version: 1.0.0
  app_bin: bin/lastrun

tasks:
  clean:
    desc: Clean the output directory
    cmds:
      - rm -rf bin
      - cargo clean
  archive.releases:
    desc: Archive the releases
    cmds:
      - |
        for i in $(gh release list --json tagName -q .[].tagName | tail -n +4); do
          gh release delete "$i" -y;
        done
  prep:
    desc: Prepare the build environment
    run: once
    cmds:
      - mkdir -p bin
  test:
    desc: Run tests
    deps:
      - prep
    cmds:
      - cargo test
  build:
    desc: Build LastRun
    deps:
      - prep
      - test
    cmds:
      - cargo build --release
      - cp target/release/lastrun {{.app_bin}}
      - shasum -a 256 {{.app_bin}} > {{.app_bin}}.sha256
