version: '3'

tasks:
  clean:
    desc: Clean the output directory
    cmds:
      - cargo clean
  archive.releases:
    desc: Archive the releases
    cmds:
      - |
        for i in $(gh release list --json tagName -q .[].tagName | tail -n +4); do
          gh release delete "$i" -y;
        done
  test:
    desc: Run tests
    cmds:
      - cargo test
  build:
    desc: Build LastRun
    deps:
      - test
    cmds:
      - cargo build --release
      - cd target/release && shasum -a 256 lastrun > lastrun.sha256
