version: '3'

tasks:
  clean:
    desc: Clean the output directory
    cmds:
      - cargo clean
  test:
    desc: Run tests
    cmds:
      - cargo test --locked
  build:
    desc: Build LastRun (optionally for a specific target, e.g. TARGET=x86_64-apple-darwin)
    cmds:
      - |
        if [ -n "{{.TARGET}}" ]; then
          rustup target add {{.TARGET}}
          cargo build --release --locked --target {{.TARGET}}
          cd target/{{.TARGET}}/release && shasum -a 256 lastrun > lastrun.sha256
        else
          cargo build --release --locked
          cd target/release && shasum -a 256 lastrun > lastrun.sha256
        fi
  install:
    desc: Build and install lastrun to ~/.cargo/bin
    cmds:
      - cargo install --path . --locked
  status:
    desc: Run the LastRun status TUI
    cmds:
      - cargo run --release -- status
  help:
    desc: Run the LastRun help
    cmds:
      - cargo run --release -- help
