name: Test

on:
  pull_request:
    branches:
      - 'master'
    paths:
      - 'Taskfile.yml'
      - 'go.mod'
      - 'go.sum'
      - '**/*.go'
      - '.github/workflows/*.yml'
      - '.github/actions/**/*.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    environment: default
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: 'go.sum'

      - name: Install Task
        run: go install github.com/go-task/task/v3/cmd/task@latest

      - name: Run Tests
        run: task test

      - name: Build App
        run: task build
