name: App Test

on:
  pull_request:
    branches:
      - 'master'
    paths:
      - 'Taskfile.yml'
      - 'Cargo.toml'
      - 'src/**/*.rs'
      - 'tests/**/*.rs'
      - '.github/workflows/test.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    environment: default
    defaults:
      run:
        shell: bash
    
    steps:
      - uses: actions/checkout@v4

      - name: Install Task
        run: pip install go-task-bin

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build App
        run: task build
